#!/bin/sh

rm -rf inst/include/stan
rm -rf inst/include/src
rm -rf inst/include/cvodes
rm -rf src/cvodes

cp -r inst/include/mathlib/stan inst/include/stan
cp -r inst/include/upstream/src inst/include/src
cp -r inst/include/mathlib/lib/cvodes_2.9.0 src/cvodes
mv inst/include/mathlib/lib/cvodes_2.9.0/include/* inst/include/

exit $?

